# Generated by Django 5.0.2 on 2024-02-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_faceencoding_name_remove_visits_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='user',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
