# Generated by Django 5.0.2 on 2024-03-05 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='entry_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
