# Generated by Django 5.0.2 on 2024-03-07 08:31

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_attendance_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='document_file',
            field=models.ImageField(upload_to=accounts.models.image_upload_path),
        ),
    ]
